name: Build Kryptis Packages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows apps
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx electron-builder --config.extraMetadata.icon=src/favicon.ico --win --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: kryptis-windows
          path: dist/**/*

  build-linux:
    name: Build Linux packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx electron-builder --config.extraMetadata.icon=src/icon.png --linux --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: kryptis-linux
          path: dist/**/*

  build-macos:
    name: Build macOS packages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx electron-builder --config.extraMetadata.icon=src/favicon.icns --mac --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: kryptis-macos
          path: dist/**/*
